### ISSUE TITLE
targetRules.safe.indexOf is not a function

### ISSUE THREAD

**Issue by justinhelmer** [Rantanen/eslint-plugin-xss#7]
When using `xss/no-mixed-html`.

Tried reinstalling all modules, attempted on different machines. All of our users are having the same issue.

Points to this bit of code in `no-mixed-html.js`:

```js
            if( targetRules.safe &&
                targetRules.safe.indexOf( tree.getNodeName( childNode ) ) !== -1 )
                return;
```

Any suggestions?

Thanks.

**Comment by Rantanen** [comment]
I was able to reproduce this by having `"foo": { "safe": true }` in the function options. The `safe` option was intended to be an array of accepted parameter names. I've now pushed v0.1.10 that also allows booleans in this position and only goes for the `indexOf` operation if the value has that. Not sure if this was the cause in your case.

**Comment by justinhelmer** [comment]
Ah, sure enough - we were using the boolean syntax for one specific use-case. Apologies for missing this, and thanks for the update to the function and the docs. Cheers.
